---

baseURL:        "http://manala.io/"
languageCode:   "en-us"
title:          "Manala project"

params:
  Subtitle: "Spinning the cogs in the widgets"
  AuthorName: "ELAO"

menu:
  main:
      - Name:       "How-to's"
        Identifier: "howto"
        URL:        "/howto"
        Weight:     80
      - Name:       "Deployment"
        Identifier: "deployment"
        URL:        "/deployment"
        Weight:     90
      - Name:       "About"
        Identifier: "about"
        URL:        "/about"
        Weight:     100
      #- Name:       "Contributors"
      #  Identifier: "contributors"
      #  URL:        "/contributors"
      #  Weight:     110
  deployment:
      - Name:       "Overview"
        URL:        "#"
        Identifier: "overview"
        Weight:     10
      - Name:       "What is the Manala deployment"
        Parent:     overview
        Identifier: "deployement_overview"
        URL:        "/deployment/overview"
        Weight:     11
      - Name:       "Getting started"
        Identifier: "getting-started"
        URL:        "#"
        Weight:     20
      - Name:       "Features"
        Parent:     getting-started
        URL:        "/deployment/features"
        Weight:     21
      - Name:       "Structure"
        Parent:     getting-started
        URL:        "/deployment/structure"
        Weight:     22
      - Name:       "Configuration"
        Parent:     getting-started
        URL:        "/deployment/configuration"
        Weight:     23
      - Name:       "Advanced configuration"
        Identifier: "advanced"
        URL:        "/deployment/advanced"
        Weight:     30
      - Name:       "Overriding"
        Parent:     advanced
        URL:        "/deployment/overriding"
        Weight:     31
